### ISSUE TITLE
Hello, I ran cchesslib-master/examples/end_game/end_game.py and the following question appeared, thanks

### ISSUE THREAD

**Issue by kdy1999** [walker8088/cchess#3]
```
C:\Users\junhao\AppData\Local\Programs\Python\Python36\python.exe D:/Download/cchesslib-master/examples/end_game/end_game.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
挑战 活挟丕豹
Traceback (most recent call last):
  File "D:/Download/cchesslib-master/examples/end_game/end_game.py", line 465, in <module>
    quit, dead_side = table.run_once()
  File "D:/Download/cchesslib-master/examples/end_game/end_game.py", line 369, in run_once
    self.draw()
  File "D:/Download/cchesslib-master/examples/end_game/end_game.py", line 206, in draw
    key = Pos(x, y)
NameError: name 'Pos' is not defined
```

**Comment by walker8088** [comment]
pygame example is deprecated, use ChessQ instead.
